import { rememberDetails,readUI,writeUI } from './ui_state.js';
import { api } from '../../../scripts/api.js';
import { readSelection } from './selection_state.js';
const modes=['Saved combined video','Pictures only','Pictures and video clips','Build combined video from selected references'];
const el=(tag,text,parent)=>{const e=document.createElement(tag);if(text)e.textContent=text;parent?.append(e);return e;};
async function request(body){const r=await api.fetchApi('/h3refcharacters/reference-selection',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to load references');return d;}
const css=`.h3rc-reference-dialog{position:fixed;inset:0;background:#080b10ba;z-index:10000;display:grid;place-items:center;color:var(--input-text,#e4eaf0);font:13px system-ui}.h3rc-reference-dialog *{box-sizing:border-box}.h3rc-reference-dialog section{background:var(--comfy-menu-bg,#18232c);border:1px solid #4c5b68;border-radius:10px;display:flex;flex-direction:column;resize:both;overflow:hidden;min-width:min(360px,96vw);min-height:300px;max-width:96vw;max-height:94vh}.h3rc-reference-dialog header,.h3rc-reference-dialog footer{padding:14px 18px;display:flex;align-items:center;gap:10px;flex-wrap:wrap;flex:none}.h3rc-reference-dialog h2{font-size:18px;margin:0;flex:1}.h3rc-reference-dialog main{min-height:0;overflow:auto;padding:0 18px 16px;flex:1}.h3rc-reference-dialog .cards{display:grid;grid-template-columns:repeat(auto-fill,minmax(min(240px,100%),1fr));gap:12px;align-items:start}.h3rc-reference-dialog article{min-width:0;border:1px solid #4c5b68;border-radius:7px;padding:10px;background:#16212b}.h3rc-reference-dialog article[data-selected=false]{opacity:.65}.h3rc-reference-dialog input,.h3rc-reference-dialog select,.h3rc-reference-dialog button{font:inherit;color:inherit;background:var(--comfy-input-bg,#121b24);border:1px solid #4c5b68;border-radius:5px;padding:7px;min-width:0;max-width:100%}.h3rc-reference-dialog select,.h3rc-reference-dialog input[type=number]{width:100%}.h3rc-reference-dialog button{cursor:pointer}.h3rc-reference-dialog button:disabled{opacity:.45}.h3rc-reference-dialog label{display:grid;gap:5px;min-width:0}.h3rc-reference-dialog .defaults{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(230px,100%),1fr));gap:12px;margin:12px 0}.h3rc-reference-dialog .media{height:155px;min-height:80px;max-height:500px;resize:vertical;overflow:hidden;background:#10151b;border-radius:4px}.h3rc-reference-dialog img,.h3rc-reference-dialog video{width:100%;height:100%;object-fit:contain}.h3rc-reference-dialog .title{display:flex;align-items:center;gap:8px;margin:8px 0}.h3rc-reference-dialog .title span{min-width:0;flex:1;overflow-wrap:anywhere}.h3rc-reference-dialog .handle{cursor:grab}.h3rc-reference-dialog small{display:block;color:#a9bbc9;line-height:1.5;margin:5px 0;overflow-wrap:anywhere}.h3rc-reference-dialog details{margin:10px 0;border-top:1px solid #40515e;padding-top:9px}.h3rc-reference-dialog summary{cursor:pointer}.h3rc-reference-dialog .status{flex:1;white-space:pre-line;min-width:min(260px,100%)}.h3rc-reference-dialog footer{border-top:1px solid #40515e}.h3rc-reference-dialog .error{color:#ffb49f}.h3rc-reference-dialog :focus-visible{outline:2px solid #8dcaff;outline-offset:2px}`;
export async function chooseReferences(node){
 const w=n=>node.widgets.find(w=>w.name===n),path=w('character_path')?.value;if(!path)throw Error('Choose a character first.');
 const data=await request({path,catalog_only:true});const selection=readSelection(w('reference_selection').value,data.character_id);let draft=selection.draft;let mode=w('visual_references').value;if(!modes.includes(mode))mode=modes[0];
 const overlay=el('div','',document.body);overlay.className='h3rc-reference-dialog';el('style',css,overlay);
 const panel=el('section','',overlay);panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.setAttribute('aria-label','Choose character references');const size=readUI(node,'chooser:size',[1000,760]);panel.style.width=Math.min(size[0],innerWidth*.94)+'px';panel.style.height=Math.min(size[1],innerHeight*.9)+'px';
 const header=el('header','',panel);el('h2','Choose references',header);const modeSelect=el('select','',header);modeSelect.style.width='min(310px,100%)';modeSelect.setAttribute('aria-label','Visual references');
 const combined=()=>mode===modes[0]||mode===modes[3];
 const eligible=m=>data.entries.filter(e=>data.external?(m!==modes[3]&&(m!==modes[1]||e.kind==='image')):((m===modes[0]||m===modes[3])?e.group==='combined':e.group!=='combined'&&(m!==modes[1]||e.kind==='image')));
 for(const m of modes){const o=el('option',m,modeSelect);o.value=m;o.disabled=!eligible(m).length;}modeSelect.value=mode;
 const reset=el('button','Reset selection',header);reset.onclick=()=>{delete draft.modes[mode];render();refresh();};
 const main=el('main','',panel);if(selection.reset)el('p','The saved selection settings are invalid. Choose references below and click Apply to replace them. Cancel keeps the current settings. Your saved character files are unchanged.',main);const defaults=el('div','',main);defaults.className='defaults';
 const budgetGroup=el('details','',main);rememberDetails(node,budgetGroup,'chooser:video-budget',false,false);el('summary','Video reference budget',budgetGroup);const budgetFields=el('div','',budgetGroup);budgetFields.className='defaults';
 const cards=el('div','',main);cards.className='cards';const footer=el('footer','',panel),status=el('div','',footer);status.className='status';status.setAttribute('role','status');const cancel=el('button','Cancel',footer),apply=el('button','Apply',footer);let revision=0,timer,dragId,closed=false;let observers=[];const previousFocus=document.activeElement;
 const close=()=>{closed=true;clearTimeout(timer);observers.forEach(o=>o.disconnect());previousFocus?.focus();writeUI(node,'chooser:size',[panel.offsetWidth,panel.offsetHeight]);document.removeEventListener('keydown',escape);overlay.remove();};const escape=e=>{if(e.key==='Tab'){const items=[...panel.querySelectorAll('button,select,input,video[controls]')].filter(x=>!x.disabled&&x.getClientRects().length);if(items.length&&((e.shiftKey&&document.activeElement===items[0])||(!e.shiftKey&&document.activeElement===items.at(-1)))){e.preventDefault();(e.shiftKey?items.at(-1):items[0]).focus();}}if(e.key==='Escape'){e.stopPropagation();close();}};document.addEventListener('keydown',escape);cancel.onclick=close;
 const config=()=>draft.modes[mode]??={selected:[...new Set(eligible(mode).filter(e=>e.indices.length).map(e=>e.source_id))],order:[...new Set(eligible(mode).map(e=>e.source_id))],defaults:{},overrides:{},budget:0};
 function select(parent,label,options,value,onchange,help){const l=el('label',label,parent),input=el('select','',l);input.setAttribute('aria-label',label);input.title=help;for(const [v,t] of options){const o=el('option',t,input);o.value=v;}if(value!=null&&!options.some(o=>o[0]===value)){const o=el('option','Unavailable — choose another profile',input);o.value=value;}input.value=value??'';input.onchange=()=>onchange(input.value);return input;}
 function render(){observers.forEach(o=>o.disconnect());observers=[];const c=config(),entries=eligible(mode);defaults.replaceChildren();cards.replaceChildren();budgetFields.replaceChildren();
  if(combined()&&!data.external){const list=[...new Map(entries.map(e=>[e.profile_id,e.profile_name])).entries()];if(c.profile===undefined)c.profile=list[0]?.[0];select(defaults,mode===modes[0]?'Saved combined profile':'Combined profile',list,c.profile,v=>{c.profile=v;render();refresh();},'One shared saved frame size for every selected source. Reordering does not change this canvas. Generation joins these encodings without resizing.');}
  else for(const kind of ['image','video']){const ids=[...new Set(entries.filter(e=>e.kind===kind&&c.selected.includes(e.source_id)).map(e=>e.source_id))];if(!entries.some(e=>e.kind===kind))continue;const common=[...new Map(entries.filter(e=>e.kind===kind&&ids.every(id=>entries.some(v=>v.source_id===id&&v.profile_id===e.profile_id&&v.indices.length))).map(e=>[e.profile_id,e.profile_name])).entries()];if(c.defaults[kind]===undefined)c.defaults[kind]=common[0]?.[0]??null;select(defaults,kind==='image'?'Default picture profile':'Default video profile',[['','Choose profiles individually'],...common],c.defaults[kind]??'',v=>{c.defaults[kind]=v||null;render();refresh();},'Applies only to selected references using the default. An explicit choice on a card takes precedence. Only profiles shared by all selected sources of this type are listed.');}
  budgetGroup.hidden=!entries.some(e=>e.kind==='video')||data.external;
  const budgetMode=select(budgetFields,'Video samples',[['all','Use all saved video samples'],['fit','Fit video samples to a token budget']],c.budget>0?'fit':'all',v=>{c.budget=v==='all'?0:Math.max(1,c.lastBudget||20480);render();refresh();},'Removing saved samples does not resize the retained data, but can change movement and reference coverage. Saved samples are not individual original frames. Pictures are protected.');
  if(c.budget>0){const label=el('label','Maximum visual reference tokens',budgetFields),input=el('input','',label);input.type='number';input.min=1;input.step=1;input.value=c.budget;input.title='Includes protected pictures and retained video samples. Similar video samples are removed first, then remaining samples are selected evenly. No pictures are automatically dropped.';input.oninput=()=>{if(input.checkValidity()){c.budget=Number(input.value);c.lastBudget=c.budget;refresh();}else apply.disabled=true;};}
  if(data.external)el('small','External: only its saved encoding is available. Source boundaries are unknown; protected video-budget reduction is unavailable.',defaults);
  const ids=[...new Set(entries.map(e=>e.source_id))].sort((a,b)=>c.order.indexOf(a)-c.order.indexOf(b));
  for(const id of ids){const versions=entries.filter(e=>e.source_id===id),entry=versions[0];const card=el('article','',cards);card.dataset.id=id;card.dataset.selected=String(c.selected.includes(id));
   const frame=el('div','',card);frame.className='media';frame.style.height=readUI(node,'chooser:preview:'+id,155)+'px';const resizeObserver=new ResizeObserver(()=>{if(frame.isConnected)writeUI(node,'chooser:preview:'+id,parseFloat(frame.style.height)||155);});resizeObserver.observe(frame);observers.push(resizeObserver);
   if(entry.preview_video||entry.preview){const media=el(entry.preview_video?'video':'img','',frame);media.src=api.apiURL('/h3refcharacters/preview?path='+encodeURIComponent(entry.preview_video||entry.preview));if(entry.preview_video){media.controls=true;media.muted=true;media.preload='metadata';}else media.alt=entry.name;}else el('small','No preview available',frame);
   const title=el('div','',card);title.className='title';const checkbox=el('input','',title);checkbox.type='checkbox';checkbox.checked=c.selected.includes(id);checkbox.disabled=mode===modes[0];checkbox.setAttribute('aria-label','Include '+entry.name);checkbox.onchange=()=>{c.selected=checkbox.checked?[...c.selected,id]:c.selected.filter(i=>i!==id);render();refresh();};el('span',entry.name,title);if(entry.filename&&entry.filename!==entry.name)el('small',entry.filename,card);
   const move=el('button','↕',title);move.className='handle';move.title='Drag to reorder; or use Alt + Up / Down.';move.setAttribute('aria-label','Move '+entry.name);move.draggable=mode!==modes[0];move.disabled=mode===modes[0];move.ondragstart=e=>{dragId=id;e.dataTransfer.setData('text/plain',id);};card.ondragover=e=>e.preventDefault();const reorder=target=>{const next=c.order.filter(i=>i!==id);next.splice(target,0,id);c.order=next;render();refresh();};card.ondrop=e=>{e.preventDefault();if(dragId&&dragId!==id){const next=c.order.filter(i=>i!==dragId);next.splice(next.indexOf(id),0,dragId);c.order=next;render();refresh();}};move.onkeydown=e=>{if(e.altKey&&['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();reorder(Math.max(0,Math.min(c.order.length-1,c.order.indexOf(id)+(e.key==='ArrowUp'?-1:1))));}};
   if(!combined()||data.external){const input=select(card,entry.kind==='image'?'Picture profile':'Video profile',[['',`Use default — ${versions.find(e=>e.profile_id===c.defaults[entry.kind])?.profile_name||'choose a default'}`],...versions.filter(e=>e.indices.length).map(e=>[e.profile_id,e.profile_name])],c.overrides[id]||'',v=>{if(v)c.overrides[id]=v;else delete c.overrides[id];refresh();},'An explicit profile overrides the matching default. Loads exactly the saved encoding; no runtime resizing.');input.disabled=!checkbox.checked;}
   const cost=el('small','Calculating…',card);cost.className='size-result';
  }
 }
 async function estimate(){if([...panel.querySelectorAll('input[type=number]')].some(e=>!e.checkValidity())){apply.disabled=true;return;}const c=config(),missing=[];
 for(const card of cards.children){
  const selected=c.selected.includes(card.dataset.id)||mode===modes[0];const versions=eligible(mode).filter(e=>e.source_id===card.dataset.id);const kind=versions[0]?.kind;const profile=combined()&&!data.external?c.profile:(c.overrides[card.dataset.id]||c.defaults[kind]);const entry=versions.find(e=>e.profile_id===profile&&e.indices.length);
  card.style.borderColor=selected&&!entry?'#ffb49f':'';const label=card.querySelector('.size-result');
  if(!selected)label.textContent='Not included in this generation';else if(!entry){label.textContent='Choose a profile here, or set the default profile above.';missing.push(card);}else label.textContent=`${entry.profile_name} · ${entry.shape[4]*16} × ${entry.shape[3]*16} · Checking cost…`;
 }
 if(missing.length){apply.disabled=true;status.classList.add('error');status.textContent=`${missing.length} selected reference(s) need a profile. Set a default above or choose a profile on each highlighted card. `;const locate=el('button','Show first unresolved reference',status);locate.onclick=()=>{missing[0].scrollIntoView({block:'center',behavior:'smooth'});missing[0].querySelector('select')?.focus({preventScroll:true});};return;}
 const rev=++revision;apply.disabled=true;status.classList.remove('error');status.textContent='Checking saved profiles…';try{const result=await request({path,settings:{visual_references:mode,reference_selection:JSON.stringify(draft)}});if(closed||rev!==revision)return;status.textContent=`${result.tokens.toLocaleString()} visual reference tokens · exact`+(result.combined?`\n${result.combined.source_count} sources · ${result.combined.dimensions.join(' × ')} · Sent to H3 as one video reference`:'\nSaved encodings are used unchanged.');for(const card of cards.children){const e=result.selected.find(e=>e.source_id===card.dataset.id);card.querySelector('.size-result').textContent=e?`${e.profile_name} · ${e.runtime_dimensions.join(' × ')} · ${e.runtime_tokens.toLocaleString()} tokens`:'Not included in this generation';}const omitted=result.report.filter(r=>r.retained_samples<r.saved_samples);if(omitted.length)status.textContent+='\n'+omitted.map(r=>`${r.source}: ${r.retained_samples} of ${r.saved_samples} video samples retained`).join('\n');apply.disabled=false;}catch(e){if(!closed&&rev===revision){status.classList.add('error');status.textContent=e.message;}}}
 function refresh(){clearTimeout(timer);apply.disabled=true;revision++;timer=setTimeout(estimate,180);}
 modeSelect.onchange=()=>{mode=modeSelect.value;render();refresh();};apply.onclick=()=>{w('visual_references').value=mode;w('reference_selection').value=JSON.stringify(draft);node.h3rcRefresh?.();node.h3rcSyncFields?.();node.graph?.setDirtyCanvas(true,true);close();};render();refresh();cancel.focus();
}
