import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";

const source = fs.readFileSync(new URL("../web/js/llm_to_jsonx.js", import.meta.url), "utf8");
const builder = fs.readFileSync(new URL("../web/js/flux_visual_builder.js", import.meta.url), "utf8");

test("JsonX frontend keeps credentials separate and exposes both preset modes", () => {
  assert.match(source, /workflowx_jsonx_gemini_api_key/);
  assert.match(source, /workflowx_jsonx_openai_api_key/);
  assert.match(source, /preset_context_mode/);
  assert.match(source, /Full preset mode/);
  assert.match(source, /Previous output kept/);
  assert.doesNotMatch(source, /setWidgetValue\(node, "ui_state"/);
});

test("LLM to JsonX stays compact and Generate feeds the flexible prompt output", () => {
  assert.match(source, /height:26px;min-height:26px/);
  assert.match(source, /height:27px;min-height:27px/);
  assert.match(source, /align-content:start/);
  assert.match(source, /const measureDomContentHeight = \(nodeWidth\) =>/);
  assert.match(source, /cloneNode\(true\)/);
  assert.match(source, /jsonx-llm-measure/);
  assert.match(source, /clone\.style\.visibility = "hidden"/);
  assert.match(source, /getMinHeight:\(\) => domMinHeight/);
  assert.match(source, /localSettings\.addEventListener\("toggle", resizeForSettings\)/);
  assert.match(source, /geminiSettings\.addEventListener\("toggle", resizeForSettings\)/);
  assert.doesNotMatch(source, /const settingsHeight =/);
  assert.doesNotMatch(source, /const expandedHeight =/);
  assert.match(source, /setWidgetValue\(node, "generated_prompt_json", finalPrompt\)/);
  assert.match(source, /Saved to prompt/);
  assert.match(source, /cancelGenerate\.textContent = "Cancel"/);
  assert.match(source, /const cancelActiveGeneration = \(\) =>/);
  assert.match(source, /new AbortController\(\)/);
  assert.match(source, /\$\{ROUTE\}\/cancel/);
  assert.match(source, /localTools\.appendChild\(refreshVramLabel\)/);
  assert.match(source, /secondaryActions\.append\(instructionSettings, cancelGenerate\)/);
  assert.match(source, /actions\.append\(status, generate, secondaryActions\)/);
  assert.match(source, /generation_id: active\.id/);
  assert.match(source, /JsonX generation cancelled\. Previous output kept\./);
  assert.match(source, /makePicker\(localPanel, "Local GGUF model"/);
  assert.match(source, /makePicker\(geminiPanel, "Gemini model"/);
  assert.match(source, /makePicker\(openaiPanel, "Fetched model"/);
  assert.match(source, /makePicker\(ollamaPanel, "Ollama model"/);
  assert.doesNotMatch(source, /function fillModels/);
  assert.doesNotMatch(source, /datalist/);
  assert.match(source, /localModel\.setOptions\(data\.models/);
  assert.match(source, /Additional model folders \(; separated\)/);
  assert.match(source, /additional_model_paths: additionalModelPaths/);
  assert.match(source, /workflowx_jsonx_provider_settings/);
  assert.match(source, /jsonx-picker-menu/);
  assert.match(source, /jsonx-picker-open/);
  assert.match(source, /for \(const item of options\)/);
  assert.doesNotMatch(source, /makeModelInput\(localPanel, "Local GGUF model"/);
  assert.match(source, /Refresh to load GGUF models/);
  assert.match(source, /No GGUF models found/);
  assert.doesNotMatch(source, /Math\.max\(680/);
  for (const setting of ["local_ctx_size", "local_max_tokens", "local_temperature", "local_top_p", "local_top_k", "local_repeat_penalty", "local_memory_mode", "local_reasoning", "local_speculative_mode", "local_mtp_draft_tokens", "local_seed"]) {
    assert.match(source, new RegExp(setting));
  }
  assert.match(source, /Local generation settings/);
  assert.match(source, /Gemini safety settings/);
  assert.match(source, /GEMINI_SAFETY_OPTIONS/);
  for (const setting of ["safety_harassment", "safety_hate_speech", "safety_sexual", "safety_dangerous"]) {
    assert.match(source, new RegExp(setting));
  }
  assert.match(source, /payload\.gemini_safety\[key\]/);
  assert.match(source, /Generated JsonX output/);
  assert.match(source, /Generated natural-language prompt/);
  assert.match(source, /outputPreview\.readOnly = true/);
  assert.match(source, /outputPreview\.value = finalPrompt/);
  assert.match(source, /Generation diagnostics/);
  assert.match(source, /Prompt feedback/);
  assert.match(source, /Candidate details/);
  assert.match(source, /error\.data = data/);
  assert.match(source, /showDiagnostics\(error\.data\?\.diagnostics\)/);
  assert.match(source, /openaiUnload\.checked/);
  assert.match(source, /ollamaThink\.checked/);
  assert.match(source, /ollamaUnload\.checked/);
  assert.match(source, /refresh_vram: refreshVram\.checked/);
  assert.match(source, /settings\[`\$\{activeBackend\}_timeout`\]/);
  assert.match(source, /host:ollamaHost\.value, timeout:Number\(timeout\.value \|\| 180\)/);
  assert.match(source, /repeat_penalty: settings\.local_repeat_penalty/);
  assert.match(source, /Auto \(detect embedded MTP\)/);
  assert.match(source, /normalizeLocalReasoning/);
  assert.match(source, /local_max_tokens: 8192/);
  assert.match(source, /local_reasoning: "off"/);
  assert.match(source, /JsonX Backend Instructions/);
  assert.match(source, /Generation profile/);
  assert.match(source, /Adaptive \(current behavior\)/);
  assert.match(source, /Template Fill \(maximum structure compliance\)/);
  assert.match(source, /Use Presets \(send full presets\.json in Template Fill\)/);
  assert.match(source, /generation_profile: generationProfileValue/);
  assert.match(source, /template_use_presets: templateUsePresetsValue/);
  assert.match(source, /Framing & placement \(3×3 rule-of-thirds map\)/);
  assert.match(source, /hideWidget\(node, "enable_framing_and_placement"\)/);
  assert.match(source, /widgetValue\(node, "enable_framing_and_placement", false\)/);
  assert.match(source, /setWidgetValue\(node, "enable_framing_and_placement", framingPlacement\.checked\)/);
  assert.match(source, /enable_framing_and_placement: framingPlacementValue/);
  assert.match(source, /enable_framing_and_placement: framingPlacement\.checked/);
  assert.doesNotMatch(source, /settings\.enable_framing_and_placement/);
  assert.match(source, /Output format and framing & placement are saved on this node and travel with the workflow/);
  assert.match(source, /Output format/);
  assert.match(source, /JsonX JSON/);
  assert.match(source, /Natural language/);
  assert.match(source, /hideWidget\(node, "output_format"\)/);
  assert.match(source, /widgetValue\(node, "output_format", "json"\)/);
  assert.match(source, /setWidgetValue\(node, "output_format", outputFormat\.value \|\| "json"\)/);
  assert.match(source, /setWidgetValue\(node, "generation_mode", "refined"\)/);
  assert.doesNotMatch(source, /settings\.output_format/);
  assert.match(source, /delete settings\["output_format"\]/);
  assert.match(source, /const INSTRUCTION_OVERRIDE_KEYS/);
  assert.match(source, /\$\{ROUTE\}\/user-settings/);
  assert.match(source, /instruction_overrides: overrides/);
  assert.match(source, /sendsFullPresets/);
  assert.match(source, /blank Template Fill hierarchy and no presets/);
  assert.match(source, /Hierarchy coverage/);
  assert.match(source, /Deep \(maximize relevant hierarchy\)/);
  assert.match(source, /Exhaustive \(maximum relevant branch coverage\)/);
  assert.match(source, /Adaptive Stage 1 system instructions/);
  assert.match(source, /Template Fill Stage 1 system instructions/);
  assert.match(source, /Refined Stage 2 system instructions/);
  assert.match(source, /Natural Language Stage 2 system instructions/);
  assert.match(source, /Effective instructions preview/);
  assert.match(source, /Reset defaults/);
  assert.match(source, /generate\.title = "Generate and save validated JsonX or natural-language output"/);
  assert.match(source, /instructionClose\.title = "Close without saving settings changes"/);
  assert.match(source, /resetInstructions\.title = "Restore packaged defaults in this editor; click Save settings to persist them"/);
  assert.match(source, /previewInstructions\.title = "Rebuild the exact effective prompts from the current unsaved editor values"/);
  assert.match(source, /saveInstructions\.title = "Save custom instructions to the ComfyUI user profile and per-node choices to this workflow"/);
  assert.match(source, /refreshVramLabel\.title = "Unload ComfyUI models and clear cache before local JsonX generation"/);
  assert.match(source, /stage_one_instructions: userInstructionOverrides\.stage_one_instructions/);
  assert.match(source, /refinement_instructions: userInstructionOverrides\.refinement_instructions/);
  assert.match(source, /natural_language_instructions: userInstructionOverrides\.natural_language_instructions/);
  assert.match(source, /output_format: outputFormatValue/);
  assert.match(source, /data\.prompt \|\| data\.prompt_json/);
  assert.match(source, /detail_level: String\(widgetValue\(node, "detail_level", "deep"\)\) \|\| "deep"/);
  assert.match(source, /instructions\/preview/);
  assert.match(source, /hierarchy_metrics/);
  assert.match(source, /leaves · depth/);
  assert.match(source, /hideWidget\(node, "generation_profile"\)/);
  assert.match(source, /hideWidget\(node, "template_use_presets"\)/);
  assert.match(source, /hideWidget\(node, "detail_level"\)/);
  assert.match(source, /setWidgetValue\(node, "generation_profile", settings\.generation_profile\)/);
  assert.match(source, /setWidgetValue\(node, "template_use_presets", settings\.template_use_presets\)/);
  assert.match(source, /setWidgetValue\(node, "detail_level", settings\.detail_level\)/);
  assert.match(source, /widgetValue\(node, "generation_profile", "adaptive"\)/);
  assert.match(source, /widgetValue\(node, "template_use_presets", false\)/);
  assert.match(source, /widgetValue\(node, "detail_level", "deep"\)/);
});

test("JsonX visual builder discovers preset roots and subject branches dynamically", () => {
  assert.match(builder, /Object\.entries\(subjectPreset \|\| \{\}\)/);
  assert.match(builder, /Object\.entries\(presets \|\| \{\}\)/);
  assert.match(builder, /interaction_suggestions/);
  assert.match(builder, /flattenPresetLibrary\(presets \|\| \{\}\)/);
  assert.match(builder, /function hydrateStateFromTemplate[\s\S]*enrichPresetBindingsFromTree\(tree\)/);
});
