import assert from "node:assert/strict";
import fs from "node:fs";
import { injectAudioXState, LOAD_AUDIO_X_DEFAULTS, movedRangeStart, normalizeAudioXState, selectedRange, timelineDragMode } from "../web/js/load_audio_x_state.mjs";

assert.deepEqual(normalizeAudioXState("bad"), LOAD_AUDIO_X_DEFAULTS);
assert.equal(normalizeAudioXState({ format: "MP3", mp3_bitrate: "999k", start: -4 }).format, "mp3");
assert.equal(normalizeAudioXState({ format: "MP3", mp3_bitrate: "999k", start: -4 }).mp3_bitrate, "192k");
assert.equal(normalizeAudioXState({ start: 12.885791666, length: 3.14159265 }).start, 12.886);
assert.equal(normalizeAudioXState({ start: 12.885791666, length: 3.14159265 }).length, 3.142);
assert.deepEqual(selectedRange({ start: 2, when_unwired: "length", length: 5 }, 20), { start: 2, length: 5, end: 7, fixed: false });
assert.deepEqual(selectedRange({ start: 2 }, 20, 3), { start: 2, length: 3, end: 5, fixed: true });
const entry = { inputs: {} };
injectAudioXState(entry, { file: "voice.m4a", channels: "Mono" });
assert.equal(JSON.parse(entry.inputs.LoadAudioXState).channels, "Mono");
assert.equal(JSON.parse(entry.inputs.LoadAudioXState).file, "voice.m4a");
assert.equal(timelineDragMode(.5, .2, .8, 600), "move");
assert.equal(timelineDragMode(.205, .2, .8, 600), "start");
assert.equal(timelineDragMode(.795, .2, .8, 600), "end");
assert.equal(timelineDragMode(.2, .2, .8, 600, true), "move");
assert.equal(movedRangeStart(2, 4, 3, 10), 5);
assert.equal(movedRangeStart(7, 4, 3, 10), 6);
assert.equal(movedRangeStart(2, 4, -8, 10), 0);
const frontend = fs.readFileSync(new URL("../web/js/load_audio_x.js", import.meta.url), "utf8");
assert.match(frontend, /fitToContent/);
assert.doesNotMatch(frontend, /getMinHeight:\(\)=>560|getMaxHeight:\(\)=>900/);
assert.match(frontend, /minWidth: 260/);
assert.doesNotMatch(frontend, /Math\.max\(420, Number\(node\.size\?\.\[0\]\)/);
assert.match(frontend, /__workflowXLoadAudioXPending/);
assert.match(frontend, /afterConfigureGraph\(\)/);
assert.match(frontend, /attachExistingNodes/);
assert.match(frontend, /height:38px;min-height:38px;max-height:38px/);
assert.doesNotMatch(frontend, /ui\.setStatus\s*=.*ui\.fitToContent/);
assert.match(frontend, /workflowx_cache/);
assert.match(frontend, /player\.pause\(\); player\.src=viewURL\(data\.preview\); player\.load\(\)/);
assert.match(frontend, /opacity:1;background:#383838/);
assert.doesNotMatch(frontend, /workflowx-lax-wave audio\{[^}]*opacity:\.92/);
assert.match(frontend, /fitToContent = \(resizeNode = false\)/);
assert.match(frontend, /if \(resizeNode && node\.__workflowXLoadAudioXRestored !== true\) \{/);
assert.match(frontend, /loadedGraphNode:attach/);
assert.match(frontend, /nodeCreated:attachCreatedNode/);
assert.match(frontend, /beforeConfigureGraph\(graphData\)\{ restoringNodeIds = new Set/);
assert.match(frontend, /restoringNodeIds\.has\(String\(node\.id\)\)/);
assert.doesNotMatch(frontend, /ui\.fitToContent\(\);\s*const configured/);
assert.match(frontend, /if \(resizeNode\) ui\.widget\?\.callback\?\.\(\)/);
assert.match(frontend, /wired!==ui\.lastWiredSeconds/);
assert.doesNotMatch(frontend, /ui\.render\(\);ui\.draw\(\);\}\},350/);
assert.match(frontend, /const DEFAULT_NODE_WIDTH = 340/);
assert.match(frontend, /const computed = node\.computeSize\?\.\(\)/);
assert.match(frontend, /grid-template-columns:repeat\(3,max-content\)/);
assert.match(frontend, /workflowx-lax-mode\{[^}]*justify-content:center/);
assert.doesNotMatch(frontend, /mode\.style\.gridTemplateColumns/);
console.log("load_audio_x_state tests passed");
