import { app } from '../../scripts/app.js';
import { api } from '../../scripts/api.js';

const NODE='WorkflowX_DetailerXMasks';
function css(){if(document.getElementById('workflowx-detailer-masks-css'))return;const s=document.createElement('style');s.id='workflowx-detailer-masks-css';s.textContent=`
.dxm{width:100%;height:100%;box-sizing:border-box;display:flex;flex-direction:column;gap:7px;padding:8px;color:var(--input-text,#ddd);font:12px system-ui;overflow:hidden}.dxm-bar{display:grid;grid-template-columns:34px minmax(0,1fr) 34px;align-items:center;gap:6px}.dxm-bar.batch{max-width:210px}.dxm button,.dxm select,.dxm input{height:28px;border:1px solid var(--border-color,#687487);border-radius:6px;background:var(--comfy-input-bg,#222);color:inherit;min-width:0}.dxm button{cursor:pointer}.dxm button:disabled{opacity:.35}.dxm-title{text-align:center;font-weight:650;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dxm-controls{display:grid;grid-template-columns:minmax(130px,1fr) auto minmax(100px,1fr);gap:7px;align-items:center}.dxm-controls select{padding:0 7px}.dxm-opacity{display:flex;align-items:center;gap:5px}.dxm-opacity input{width:110px;accent-color:#8eb0ff}.dxm-color{width:36px!important;padding:2px!important}.dxm-view{position:relative;flex:1;min-height:250px;background:#090a0c;border:1px solid #3c424b;border-radius:7px;overflow:hidden;display:flex;align-items:center;justify-content:center}.dxm-view.zoom{display:block;overflow:auto}.dxm-view img{display:block;max-width:100%;max-height:100%;object-fit:contain;user-select:none;-webkit-user-drag:none}.dxm-view.zoom img{max-width:none;max-height:none;margin:auto}.dxm-overlay{position:absolute;inset:0;background:var(--mask-color,#ff3355);opacity:var(--mask-opacity,.55);mask-image:var(--mask-url);-webkit-mask-image:var(--mask-url);mask-repeat:no-repeat;-webkit-mask-repeat:no-repeat;mask-position:center;-webkit-mask-position:center;mask-size:contain;-webkit-mask-size:contain;pointer-events:none}.dxm-info{min-height:34px;padding:6px 8px;border:1px solid #ffffff18;border-radius:6px;color:#bfc9da;overflow:auto}.dxm-footer{display:flex;justify-content:space-between;align-items:center;gap:7px}.dxm-actions{display:flex;gap:6px}.dxm-empty{padding:20px;text-align:center;color:#aaa}.dxm-modal{position:fixed;inset:0;z-index:100000;background:#000e;display:flex;align-items:center;justify-content:center;padding:24px}.dxm-modal .dxm-canvas{position:relative;max-width:96vw;max-height:92vh}.dxm-modal img{display:block;max-width:96vw;max-height:92vh}.dxm-modal>button{position:absolute;right:24px;top:18px;width:40px;height:40px;font-size:24px;background:#222;color:#fff;border:1px solid #777;border-radius:7px}
`;document.head.append(s);}
function url(item){return item?api.apiURL('/view?'+new URLSearchParams({filename:item.filename,subfolder:item.subfolder||'',type:item.type||'temp'})):'';}
function payload(message){let v=message?.workflowx_detailer_masks;if(Array.isArray(v))v=v[0];return v&&typeof v==='object'?v:null;}
function button(text,title,fn){const b=document.createElement('button');b.type='button';b.textContent=text;b.title=title;b.addEventListener('click',fn);return b;}
function persist(node){node.properties??={};const s=node._dxm;node.properties.detailer_x_masks={stage:s.stage,batch:s.batch,kind:s.kind,opacity:s.opacity,color:s.color,zoom:s.zoom};}
function restore(node){const p=node.properties?.detailer_x_masks||{},opacity=Number(p.opacity);return{stage:Number(p.stage)||0,batch:Number(p.batch)||0,kind:['detector','refined','blend'].includes(p.kind)?p.kind:'blend',opacity:Number.isFinite(opacity)?Math.max(0,Math.min(1,opacity)):.55,color:/^#[0-9a-f]{6}$/i.test(p.color||'')?p.color:'#ff3355',zoom:Boolean(p.zoom),data:null};}
function overlay(view,baseUrl,maskUrl,state){const img=document.createElement('img');img.src=baseUrl;img.alt='Detailer input image';const layer=document.createElement('div');layer.className='dxm-overlay';layer.style.setProperty('--mask-url',`url("${maskUrl}")`);layer.style.setProperty('--mask-color',state.color);layer.style.setProperty('--mask-opacity',state.opacity);view.append(img,layer);}
function modal(baseUrl,maskUrl,state){const m=document.createElement('div');m.className='dxm-modal';m.tabIndex=0;const canvas=document.createElement('div');canvas.className='dxm-canvas';overlay(canvas,baseUrl,maskUrl,state);const close=button('×','Close enlarged mask overlay',()=>m.remove());m.append(canvas,close);m.addEventListener('click',e=>{if(e.target===m)m.remove();});m.addEventListener('keydown',e=>{if(e.key==='Escape')m.remove();});document.body.append(m);m.focus();}
function render(node){const s=node._dxm,root=node._dxmRoot,d=s.data;root.replaceChildren();if(!d?.stages?.length){const e=document.createElement('div');e.className='dxm-empty';e.textContent=d?.bypass_reason||'Run an enabled DetailerX detailer to inspect its masks.';root.append(e);return;}s.stage=Math.max(0,Math.min(s.stage,d.stages.length-1));const item=d.stages[s.stage],count=d.stages.length,batches=item.inputs?.length||1;s.batch=Math.max(0,Math.min(s.batch,batches-1));
 const bar=document.createElement('div');bar.className='dxm-bar';const prev=button('‹','Previous detailer mask',()=>{s.stage=(s.stage-1+count)%count;s.batch=0;persist(node);render(node);}),title=document.createElement('div'),next=button('›','Next detailer mask',()=>{s.stage=(s.stage+1)%count;s.batch=0;persist(node);render(node);});title.className='dxm-title';title.textContent=item.name;title.title=item.name;prev.disabled=next.disabled=count<2;bar.append(prev,title,next);
 const controls=document.createElement('div');controls.className='dxm-controls';const select=document.createElement('select');select.title='Choose which mask stage to overlay';for(const [v,label] of [['detector','Detector proposal'],['refined','SAM-refined mask'],['blend','Final blend mask']]){const o=document.createElement('option');o.value=v;o.textContent=label;select.append(o);}select.value=s.kind;select.addEventListener('change',()=>{s.kind=select.value;persist(node);render(node);});const color=document.createElement('input');color.type='color';color.className='dxm-color';color.value=s.color;color.title='Mask overlay color';color.addEventListener('input',()=>{s.color=color.value;persist(node);render(node);});const opacity=document.createElement('label');opacity.className='dxm-opacity';opacity.textContent='Opacity';const range=document.createElement('input');range.type='range';range.min=0;range.max=1;range.step=.05;range.value=s.opacity;range.title='Mask overlay opacity';range.addEventListener('input',()=>{s.opacity=Number(range.value);root.querySelectorAll('.dxm-overlay').forEach(x=>x.style.setProperty('--mask-opacity',s.opacity));});range.addEventListener('change',()=>persist(node));opacity.append(range);controls.append(select,color,opacity);
 const baseUrl=url(item.inputs?.[s.batch]),maskUrl=url(item.masks?.[s.kind]?.[s.batch]);const view=document.createElement('div');view.className='dxm-view'+(s.zoom?' zoom':'');overlay(view,baseUrl,maskUrl,s);
 const info=document.createElement('div');info.className='dxm-info';const regions=item.region_counts?.[s.batch]??0,processed=item.processed_counts?.[s.batch]??0,classes=(item.classes||[]).join(', ')||'all classes';info.textContent=`${item.messages?.[s.batch]||`${regions} region(s), ${processed} processed`} · ${item.backend||'detector-only'} · ${classes}`;info.title=`Detector: ${item.detector||'none'}\nState: ${item.state||''}`;
 const footer=document.createElement('div');footer.className='dxm-footer';const batch=document.createElement('div');batch.className='dxm-bar batch';const bp=button('‹','Previous image in batch',()=>{s.batch=(s.batch-1+batches)%batches;persist(node);render(node);}),bt=document.createElement('div'),bn=button('›','Next image in batch',()=>{s.batch=(s.batch+1)%batches;persist(node);render(node);});bt.className='dxm-title';bt.textContent=`Image ${s.batch+1} / ${batches}`;bp.disabled=bn.disabled=batches<2;batch.append(bp,bt,bn);const actions=document.createElement('div');actions.className='dxm-actions';actions.append(button(s.zoom?'Fit':'100%','Toggle fitted or pixel-size view',()=>{s.zoom=!s.zoom;persist(node);render(node);}),button('Enlarge','Open enlarged mask overlay',()=>modal(baseUrl,maskUrl,s)));footer.append(batch,actions);root.append(bar,controls,view,info,footer);node.setDirtyCanvas?.(true,true);}
app.registerExtension({name:'workflowx.detailer_x_masks',async beforeRegisterNodeDef(type,data){if(data.name!==NODE)return;const created=type.prototype.onNodeCreated;type.prototype.onNodeCreated=function(){created?.apply(this,arguments);css();this._dxm=restore(this);const root=document.createElement('div');root.className='dxm';for(const event of ['pointerdown','pointerup','wheel','keydown'])root.addEventListener(event,e=>e.stopPropagation());this._dxmRoot=root;const widget=this.addDOMWidget('detailer_x_masks','DetailerXMasks',root,{serialize:false,hideOnZoom:false,getMinHeight:()=>420,getMaxHeight:()=>1200});widget.computeSize=()=>[500,460];this.setSize([Math.max(520,this.size?.[0]||0),Math.max(560,this.size?.[1]||0)]);render(this);};const executed=type.prototype.onExecuted;type.prototype.onExecuted=function(message){executed?.apply(this,arguments);this._dxm.data=payload(message);this._dxm.stage=Math.min(this._dxm.stage,Math.max(0,(this._dxm.data?.stages?.length||1)-1));render(this);};const configured=type.prototype.onConfigure;type.prototype.onConfigure=function(info){configured?.apply(this,arguments);this._dxm={...restore(this),data:null};render(this);};}});
