export const HELP = {
  pause_minutes:"Minutes from node entry until processing automatically resumes. Updating this value recalculates the deadline from the original entry time.",
  wait_indefinitely:"Wait for Resume, Skip, or Cancel instead of automatically resuming. The current queue job remains open; ComfyUI interrupt is still available.",
  preset:"Apply a model-family/variant sampling preset to all five detailers. This does not load or replace MODEL, CLIP or VAE. Modified indicates node-local overrides.",
  enabled:"Enable this processor. Disabled stages pass through their input unchanged and retain their settings.",
  steps:"Actual detail-crop sampling steps. At partial denoise, a longer schedule is built and its final steps are used. Few-step model presets are starting points, not validated low-denoise optima.",
  cfg:"Comfy classifier-free guidance: higher values strengthen positive versus negative conditioning. At CFG 1, negative prompting has no effect. This is separate from FLUX embedded guidance. Krea's published guidance is Comfy CFG minus one.",
  guidance_mode:"Incoming preserves encoded guidance; Set writes the value after local prompt encoding; Disabled removes embedded guidance. This is independent of CFG.",
  guidance:"Embedded FLUX guidance, used only when Guidance Mode is Set. It is not the CFG scale and does not enable negative prompting.",
  sampler_name:"Numerical denoising method. Presets choose family-appropriate starting methods; incompatible custom choices may fail in ComfyUI.",
  scheduler:"Noise distribution across steps. Flux2 and Krea2 use actual encoded crop dimensions; other schedules use the supplied model's sampling configuration without replacing upstream patches.",
  denoise:"Crop redraw strength from 0 to 1. Zero bypasses detailing. Higher values permit larger changes and can alter identity or anatomy.",
  guide_size:"Target short-edge size in pixels for the crop, or detected bounding box when Guide Size For is enabled.",
  guide_size_for:"When enabled, size the detected bounding box to Guide Size rather than the full expanded crop.",
  max_size:"Maximum sampled crop edge in pixels. Larger crops use more VRAM; aspect ratio is retained.",
  cycle:"Number of repeated sampling passes per detected region; increases processing time.",
  seed:"Noise seed. Fixed mode repeats it; random mode chooses a new seed on execution. Grain has its own seed.",
  seed_mode:"Fixed repeats the seed. Random changes diffusion noise per execution. Time grain realizes fresh randomness when its stage invalidates; downstream-only edits retain cached grain.",
  detector:"Ultralytics bounding-box detector. Internal files are packaged locally; Comfy files come from registered model paths.",
  model:"Select a model using its portable internal or registered ComfyUI identifier. Full asset paths appear in the selector.",
  prompt:"Local detail prompt. Used according to Prompt Mode; the incoming negative conditioning is retained.",
  prompt_mode:"Incoming uses connected positive conditioning; Replace encodes the local prompt; Concat combines local and incoming conditioning.",
  feather:"Compositing mask blur radius in pixels. Softens the boundary between the refined crop and the original image.",
  noise_mask:"Limit denoising using the detection/SAM mask instead of redrawing the entire crop.",
  force_inpaint:"Refine even when the detected region already meets the guide size.",
  bbox_threshold:"Detector confidence cutoff (0–1). Higher values reject uncertain detections.",
  bbox_dilation:"Expand positive or shrink negative detection masks, in pixels.",
  bbox_crop_factor:"Multiplier expanding the crop around the detected box to provide context.",
  sam_detection_hint:"Point/box hints used by shared SAM to refine the detected region mask.",
  sam_dilation:"Expand or shrink the SAM mask in pixels after segmentation.",
  sam_threshold:"SAM confidence cutoff (0–1); the best mask is used if none reaches the cutoff.",
  sam_bbox_expansion:"Expand the bounding-box hint passed to SAM, in pixels.",
  sam_mask_hint_threshold:"Foreground cutoff for mask-area SAM point hints.",
  sam_mask_hint_use_negative:"Whether background points help SAM reject areas outside the target. Names retain workflow compatibility.",
  drop_size:"Ignore detections smaller than this pixel size.",
  inpaint_model:"Use core inpaint conditioning for an inpaint-compatible model. Leave off for ordinary text-to-image models.",
  noise_mask_feather:"Blur noise-mask edges in pixels. Enables differential diffusion when needed, preserving an existing upstream patch.",
  tiled_encode:"Encode VAE crops in tiles to reduce peak VRAM, potentially changing tile-boundary results.",
  tiled_decode:"Decode VAE crops in tiles to reduce peak VRAM. RGB/RGBA normalization and original alpha preservation still apply.",
  device:"Shared SAM device preference. Applies to all detailers even when face detailing is disabled.",
  mode:"Rescale multiplies input dimensions; Resize targets the configured width while retaining aspect ratio.",
  rescale_factor:"Output width and height multiplier after model upscaling.",
  resize_width:"Target output width in pixels when Resize mode is selected.",
  resampling_method:"Interpolation used for the final upscale resize.",
  supersample:"Resize through a larger intermediate image before the final output size.",
  rounding_modulus:"Round Resize output dimensions to multiples of this pixel value.",
  brightness:"Brightness multiplier; 1 leaves brightness unchanged.",
  contrast:"Contrast multiplier; 1 leaves contrast unchanged.",
  saturation:"Color saturation multiplier; 1 is unchanged and 0 is grayscale.",
  grain_power:"Strength of generated film grain; 0 removes grain.",
  grain_scale:"Spatial scale of the grain pattern; larger values produce coarser grain.",
  grain_sat:"Colorfulness of the grain: 0 is monochrome.",
  H:"Hue offset in the workflow's 0–255 HSV scale.",
  S:"Saturation offset in the workflow's 0–255 HSV scale.",
  V:"Value/brightness offset in the workflow's 0–255 HSV scale.",
  channel:"Color channel adjusted by Levels; RGB adjusts all color channels.",
  black_point:"Input level mapped to output black, on a 0–255 scale.",
  white_point:"Input level mapped to output white, on a 0–255 scale.",
  gray_point:"Midtone/gamma adjustment for Levels; 1 is neutral.",
  output_black_point:"Output black level on a 0–255 scale.",
  output_white_point:"Output white level on a 0–255 scale.",
  iterations:"Lucy sharpening iterations; more can emphasize halos and noise.",
  kernel_size:"Sharpening kernel size; controls the spatial scale of recovered detail.",
  upscaling_mode:"DLSS output scale. Native/DLAA preserves size; other modes increase or target output dimensions.",
  style:"DLSS neural-rendering style. Off bypasses neural rendering.",
  intensity:"Overall DLSS neural-rendering strength.",
  tone:"DLSS tonal adjustment strength.",
  structure:"DLSS structure preservation/control strength; workflow baseline is 1.25.",
  skin:"DLSS skin adjustment; -1 uses the runtime default.",
  auto_mask:"Enable DLSS automatic masking.",
  motion:"DLSS motion estimation method; Auto chooses the available backend.",
  scene_change_threshold:"Threshold for resetting temporal history when image content changes.",
  batch_mode:"Temporal sequence shares history across batch frames; Still Images processes unrelated images independently.",
  warmup_frames:"Extra DLSS initialization frames; increases processing time.",
  backend:"DLSS execution backend. Auto selects the platform-compatible bundled runtime.",
  channel_order:"DLSS bridge pixel-channel order. Auto selects the runtime convention.",
  hdr:"Enable the runtime HDR path; leave off for ordinary SDR workflow images.",
  global_tone:"Global DLSS tone override; -1 retains the runtime default.",
  detail:"DLSS detail control; workflow baseline is 0.3.",
  color:"DLSS color control; workflow baseline is 0.3.",
};
export function helpText(section,key) {
  const finishing={R:'Red channel offset in 8-bit levels (-255 to 255).',G:'Green channel offset in 8-bit levels (-255 to 255).',B:'Blue channel offset in 8-bit levels (-255 to 255).',gamma:'Power-law gamma: 1 is neutral; larger values darken midtones.',adjust_type:'Tonal region receiving the color balance adjustment.',cyan_red:'Red-channel adjustment in the selected tonal range.',magenta_green:'Green-channel adjustment in the selected tonal range.',yellow_blue:'Yellow/blue adjustment in the selected tonal range.',preserve_luminosity:'Rescale adjusted colors to retain their original luminance where possible.',kelvin:'Source illuminant in Kelvin, corrected toward 6500 K. Lower source Kelvin cools the image. 6500 is an exact no-op. Approximate correction, not automatic white balance or tint correction.',lens_shape:'Shape of the radial lens effect.',lens_edge:'Around uses the image bounds; symmetric uses a centered square radial field.',lens_curvy:'Curvature of the radial effect.',lens_zoom:'Scale of the radial field.',lens_aperture:'Strength of radial pixel displacement.',blur_intensity:'Even blur control; 2 adds no extra blur. Larger values soften outer regions.',magnitude:'Uniform pixel perturbation amplitude as a fraction of 255 intensity levels.',grain_size:'GrainNet conditioning size; controls the learned grain pattern.',strength:'Amount of learned monochrome grain added to RGB.',lut:'Portable .cube LUT asset from internal or installed LayerStyle locations.',color_space:'Linear applies LUT directly; log uses the reference gamma-encoded mapping.',lut_strength:'LUT blend percentage, 0–100.',initial_jpeg_quality:'JPEG quality of the camera simulation roundtrip. Returns pixels; does not save a file.',vignette_strength:'Darkening toward image corners.',chroma_aberr_strength:'Seeded red/blue channel displacement in pixels.',bayer_demosaic:'Simulate sensor mosaic and reconstruction; may soften fine detail.',iso_noise_scale:'Reference sensor gain/noise scale. 1 is baseline; changing it also changes brightness.',sensor_read_noise:'Standard deviation of sensor read noise in 8-bit levels.',hot_pixel_prob:'Fraction of pixels replaced by bright sensor defects.',banding_strength:'Strength of horizontal sensor banding.',motion_blur_kernel:'Horizontal blur kernel in pixels; even values are rounded up to odd.',cycles:'Number of in-memory JPEG compression/decompression passes.',min_quality:'Minimum randomized JPEG quality per pass.',max_quality:'Maximum randomized JPEG quality per pass.'};
  if(section==='color_balance'&&key==='magenta_green')return 'Reference convention: positive adds magenta and subtracts green; negative adds green.';
  if(finishing[key])return finishing[key];
  if(section==="dlss5" && key==="preset")return "DLSS runtime preset index; independent of the DetailerX model-family preset.";
  return HELP[key] || `Configure ${key.replaceAll("_"," ")} for ${section}. Saved in this node's workflow settings.`;
}
