"""Deterministic native H3 prompt compiler; never parses free prose into bindings."""
import re
import json
PARTS=re.compile(r'(<d>.*?</d>)',re.S)
MENTION=re.compile(r'@@|(?<![\w@])@([a-zA-Z0-9_-]+)')
LABEL={'image':'Picture','video':'Video','audio':'Audio'}
ROLE_GUIDANCE={'association':'Use the described reference details for the associated character; do not introduce another character.', 'character appearance':'Retain this character visual identity.', 'wardrobe':'Use the referenced clothing and accessories.', 'scene':'Use the environment and its fixtures; do not transfer people from this scene source.', 'prop':'Use the referenced object.', 'style':'Transfer visual style without copying source identities.', 'motion':'Use the referenced motion while retaining the target character identity.', 'performance':'Use the referenced performance while retaining the target character identity.', 'camera':'Use the camera movement and framing from this video.'}
def preservation_rule(ref, automatic, instruction):
    explicit=ref.get('reference_type')
    if explicit:
        if explicit not in ('fully_preserved','partially_preserved','attribute_transfer','weak_reference'): raise ValueError('Invalid visual Reference type.')
        from .media import transfer_text
        return explicit,instruction(transfer_text(ref.get('retain',''),ref.get('change','')))
    mode=ref.get('preservation','Automatic by role')
    if mode not in ('Automatic by role','Full','Custom','Weak reference'): raise ValueError('Unknown preservation mode.')
    from .media import transfer_text
    text=transfer_text(ref.get('retain',''),ref.get('change','')) or ref.get('preservation_text','').strip()
    if mode=='Automatic by role' and text: mode='Custom'
    if mode=='Custom' and not text: return automatic, ''
    return ({'Automatic by role':automatic,'Full':'fully_preserved','Custom':'partially_preserved','Weak reference':'weak_reference'}[mode], instruction(text) if mode in ('Custom','Weak reference') else '')

SECTIONS=['subject_definitions','summary','retention_analysis','detailed_description','overall_soundscape','non_diegetic_music']


def outside(prompt): return ''.join(p if not p.startswith('<d>') else ' ' for p in PARTS.split(prompt))


def resolve(prompt,characters):
    if prompt.count('<d>')!=prompt.count('</d>'): raise ValueError('Every <d> dialogue span needs a closing </d>.')
    available={}
    for c in characters or []:
        a=c['alias'].lower()
        if a in available and json.dumps(available[a],sort_keys=True,default=str)!=json.dumps(c,sort_keys=True,default=str):
            raise ValueError(f'Conflicting selected character @{a}. Repeated connections must use identical selections, voice and transfer settings.')
        available[a]=c
    for m in MENTION.finditer(outside(prompt)):
        if m[1] and m[1].lower() not in available: raise ValueError(f'Unknown @{m[1]}. Connect that character or named reference.')
    return list(available.values())


def compile_prompt(prompt,active,refs):
    if prompt.count('<d>')!=prompt.count('</d>'): raise ValueError('Every <d> dialogue span needs a closing </d>.')
    body=outside(prompt)
    if re.search(r'(?im)^\s*subject_definitions\s*:',body): raise ValueError('subject_definitions are generated by the node. Keep your scene and regular-reference instructions in the scene prompt.')
    subjects={c['alias'].lower():i+1 for i,c in enumerate(active)}
    aliases={a:f'<Subject {n}>' for a,n in subjects.items()}
    counts=dict(image=0,video=0,audio=0)
    for r in refs:
        counts[r['kind']]+=1;r['label']=f"<{LABEL[r['kind']]} {counts[r['kind']]}>"
        if r.get('tag') and r['tag'] not in aliases: aliases[r['tag']]=r['label']
        if r.get('owner') and r['owner'] not in subjects: raise ValueError(f"Reference association @{r['owner']} must be connected as a character.")
    # Named non-character visuals expand directly to their content and all allocated source labels.
    for tag in {r.get('tag') for r in refs if r.get('category')=='named' and r['kind']!='audio'}:
        if tag in subjects: continue
        rows=[r for r in refs if r.get('tag')==tag and r['kind']!='audio']
        text=str(rows[0].get('descriptor','')).strip()
        if MENTION.search(text) or re.search(r'[<>\r\n]',text):
            raise ValueError(f'@{tag}: Descriptor must be plain text without @tags, H3 labels or newlines.')
        aliases[tag]=(text+' from ' if text else '')+', '.join(r['label'] for r in rows)
    voice_tags={}
    for r in refs:
        target=r.get('target') or r.get('owner')
        if r['kind']!='audio' or r.get('role','character voice')!='character voice' or target not in subjects: continue
        automatic=target+'-voice'
        matching=[x for x in refs if x.get('tag')==automatic]
        if automatic in subjects or any(x['kind']!='audio' or x.get('role')!='character voice' or (x.get('target') or x.get('owner'))!=target for x in matching):
            raise ValueError(f'@{automatic} is reserved for @{target} voice. Rename the conflicting tag.')
        voice_tags[automatic]=target
        if r.get('tag'): voice_tags[r['tag']]=target
    for tag,target in voice_tags.items(): aliases[tag]=aliases[target]
    for m in MENTION.finditer(body):
        if m[1] and m[1].lower() not in aliases:
            tag=m[1].lower()
            if tag.endswith('-voice') and tag[:-6] in subjects: raise ValueError(f'@{tag} has no active voice. Enable Use saved voice or associate a character-voice audio reference with @{tag[:-6]}.')
            raise ValueError(f'Unknown @{m[1]}. Connect the corresponding character or named reference.')
    for m in re.finditer(r'<(Picture|Video|Audio)\s+(\d+)>',body,re.I):
        kind=next(k for k,v in LABEL.items() if v.lower()==m[1].lower())
        if not 1<=int(m[2])<=counts[kind]: raise ValueError(f'No reference exists for {m[0]}. Check Reference and voice assignments.')
    if re.search(r'<Subject\s+\d+>',body,re.I): raise ValueError('Use @tags instead of manual <Subject N> labels.')
    # Only explicit character vocal events in shot prose establish speaker order.
    section=re.search(r'(?im)^detailed_description\s*:',body)
    shot_body=body[section.end():] if section else body
    shot_body=re.split(r'(?im)^(?:overall_soundscape|non_diegetic_music)\s*:',shot_body)[0]
    speakers={}; characters={c['alias'] for c in active if not c.get('temporary') or c.get('is_character')}
    for m in MENTION.finditer(shot_body):
        if not m[1]: continue
        tag=m[1].lower();a=voice_tags.get(tag)
        if a is None and tag in characters and re.match(r'\s*:',shot_body[m.end():]): a=tag
        if a is not None and a not in speakers: speakers[a]=len(speakers)+1
    for tag,target in voice_tags.items():
        if target not in speakers and any(m[1] and m[1].lower()==tag for m in MENTION.finditer(body)):
            speakers[target]=len(speakers)+1
        aliases[tag]=aliases[target]+(f' (S{speakers[target]})' if target in speakers else '')
    for m in re.finditer(r'(?<![\w@])@([a-zA-Z0-9_-]+)\s*:\s*\(S(\d+)\)',body):
        if speakers.get(m[1].lower())!=int(m[2]): raise ValueError('Manual speaker annotation conflicts with first vocal-event order.')
    manual=re.sub(r'(?<![\w@])@[\w-]+\s*:\s*\(S\d+\)','',body)
    if active and re.search(r'\(S\d+\)',manual): raise ValueError('Put manual speaker annotations directly after @character:, or let the node generate them.')
    def sub(m): return '@' if m[0]=='@@' else aliases[m[1].lower()]
    chunks=[]
    for p in PARTS.split(prompt):
        if p.startswith('<d>'): chunks.append(p);continue
        def speaker(m):
            a=m[1].lower()
            if a in voice_tags: return aliases[a]+':'
            if a not in speakers: return aliases[a]+':'
            return f'{aliases[a]} (S{speakers[a]}):'
        p=re.sub(r'(?<![\w@])@([a-zA-Z0-9_-]+)\s*:(?:\s*\(S\d+\))?',speaker,p)
        chunks.append(MENTION.sub(sub,p))
    def instruction(text):
        if '<d>' in text or re.search(r'(?im)^('+ '|'.join(SECTIONS)+r')\s*:',text):
            raise ValueError('Keep dialogue and H3 sections in the main scene prompt; use reference instructions only for transfer guidance.')
        for m in MENTION.finditer(text):
            if m[1] and m[1].lower() not in aliases: raise ValueError(f'Unknown @{m[1]} in reference instructions.')
        return MENTION.sub(sub,text)
    definitions=[];retention=[];mapping=[]
    for c in active:
        a=c['alias']; visual=', '.join(r['label'] for r in refs if r.get('owner')==a and r['kind']!='audio')
        voice=', '.join(r['label'] for r in refs if (r.get('target') or r.get('owner'))==a and r['kind']=='audio' and r.get('role','character voice')=='character voice')
        # Catalog names/descriptions can be filenames or dataset notes, not model instructions.
        role=c.get('role','appearance')
        if c.get('temporary'):
            definitions.append(f'{aliases[a]}: {role} from {visual}.' if visual else f'{aliases[a]} is a subject in the scene.')
        else:
            identity=instruction(str(c.get('descriptor','')).strip()) or 'a character'
            definitions.append(f'{aliases[a]} is {identity}'+(f'; identity from {visual}.' if visual else '.'))
        from .media import transfer_text
        descriptor=transfer_text(c.get('retain',''),c.get('change','')).strip()
        if descriptor:
            for m in MENTION.finditer(outside(descriptor)):
                if m[1] and m[1].lower() not in aliases: raise ValueError(f'Unknown @{m[1]} in appearance instructions.')
            descriptor=instruction(descriptor)
        if c.get('temporary'):
            role=c.get('role','character appearance');target=c.get('target','')
            marker='attribute_transfer' if target else 'weak_reference' if role=='style' else 'fully_preserved'
            marker,keep=preservation_rule(c,marker,instruction)
            retention.append(f'{aliases[a]}: {marker} - '+(keep or ROLE_GUIDANCE.get(role,'Use the defined reference role.'))+(f' Target: {aliases[target]}.' if target else '')+' '+instruction(c.get('description','')))
        else:
            guidance=descriptor or 'Retain identity and overall appearance.'
            retention.append(f'{aliases[a]}: '+('fully_preserved' if not descriptor else 'partially_preserved')+f' - {guidance}')
        mapping.append(f'@{a} -> {aliases[a]}'+(f' (S{speakers[a]})' if a in speakers else ' (no vocal event)')+f' | visuals: {visual or "none"} | voice: {voice or "none"}')
    for r in refs:
        role=r.get('role','regular reference');target=r.get('target') or r.get('owner'); label=r['label'];instructions=instruction(r.get('instructions',''))
        if r.get('category')=='named' or (r['kind']=='audio' and target):
            definition=f'{label}: {role}'+(f' for {aliases[target]}' if target else '')+'.'
            if r['kind']=='audio' and role=='character voice':
                definition=f'{label} is the voice-timbre reference for {aliases[target]}'+(f' (S{speakers[target]})' if target in speakers else '')+'.'
            if r['kind']!='audio' and r.get('tag') not in subjects:
                content=str(r.get('descriptor','')).strip()
                definition=f'{label}: '+(content+'; ' if content else '')+f'{role} reference'+(f' for {aliases[target]}' if target else '')+'.'
            if role=='custom':
                definition=f'{label} is {str(r.get("descriptor","")).strip().rstrip(".") }.'
            if role=='association' and target:
                definition=f'{label} is {str(r.get("descriptor","")).strip()} belonging to {aliases[target]}.'
            definitions.append(definition)
            if r['kind']=='audio':
                guidance=instructions or ('Transfer voice timbre to the requested new dialogue.' if role=='character voice' else 'Use this audio according to its description and the scene instructions.')
                marker=r.get('reference_type')
                if marker and marker not in ('reference','weak_reference','partially_copy','fully_copy'): raise ValueError('Invalid audio Reference type.')
                retention.append(f'{label}: '+(marker+' - ' if marker else '')+guidance)
            elif r.get('tag') not in subjects:
                marker='attribute_transfer' if target else 'weak_reference' if role in ('style','camera') else 'fully_preserved'
                marker,keep=preservation_rule(r,marker,instruction)
                retention.append(f'{label}: {marker} - '+(keep or ROLE_GUIDANCE.get(role,'Use the defined reference role.'))+' '+instructions)
        cost=f'{r["tokens"]} tokens' if 'tokens' in r else 'estimate pending preprocessing'
        if r.get('paired'): cost='audio cost included in paired video block'
        mapping.append(f'{label} | @{r.get("tag") or r.get("owner") or "raw"} | {r.get("source","reference")} | {role} | target: {target or "none"} | {r.get("duration","n/a")} seconds | {cost}'+(f' | original {r["original_tokens"]}' if 'original_tokens' in r else '')+(f' | assembled from {r["runtime_combined"]["source_count"]} selected sources | shape {r["shape"]}' if r.get('runtime_combined') else f' | shape {r["original_shape"]} -> {r["shape"]}' if 'shape' in r else ''))
    for tag,expansion in aliases.items():
        if tag not in subjects: mapping.append(f'@{tag} -> {expansion}')
    expanded=''.join(chunks)
    # Preserve regular-only native prompts byte-for-byte, enabling conditioning parity.
    if not active and not any(r.get('category')=='named' for r in refs): return expanded,'\n'.join(mapping)
    masked=PARTS.sub(lambda m:' '*len(m[0]),expanded)
    matches=list(re.finditer(r'(?im)^('+ '|'.join(SECTIONS[1:])+r')\s*:',masked))
    sections={k:'' for k in SECTIONS}
    if matches:
        prefix=expanded[:matches[0].start()].strip()
        if prefix: sections['detailed_description']=prefix+'\n'
        for i,m in enumerate(matches):
            key=m[1].lower()
            sections[key]+=expanded[m.end():matches[i+1].start() if i+1<len(matches) else len(expanded)].strip()+'\n'
    else: sections['detailed_description']=expanded
    sections['subject_definitions']='\n'.join(definitions)
    if not re.match(r'^\s*\[',sections['summary']):
        tasks=['reference generation']
        if any(r['kind']=='audio' and r.get('category')!='raw' for r in refs): tasks.append('audio reference')
        sections['summary']='['+' + '.join(tasks)+'] '+sections['summary']
    sections['retention_analysis']='\n'.join(retention)+'\n'+sections['retention_analysis']
    mapping.append('Associations above are declared in nodes. Free-text regular-reference instructions are preserved, not parsed into associations.')
    return '\n\n'.join(k+':\n'+sections[k].strip() for k in SECTIONS),'\n'.join(mapping)
